# default controller

index:
    path: /
    controller: App\Controller\DefaultController::Index

# security routing for user
security_login:
    path: /login
    controller: App\Controller\SecurityController::Login


security_account:
    path: /account/{id}
    controller: App\Controller\SecurityController::Account
    requirements:
        id: '\d+'

# Site Controller
site_list:
<<<<<<< HEAD
    path: admin/site
=======
    path: /site
>>>>>>> 1b8374ec344e06bfa94cc4e4c8b34112ec9c3496
    controller: App\Controller\SiteController::List

site_update:
    path: /site/update/{id}
    controller: App\Controller\SiteController::Update
    requirements:
        id: '\d+'

site_delete:
    path: /site/delete/{id}
    controller: App\Controller\SiteController::Delete
    requirements:
        id: '\d+'

site_search:
    path: /site
    controller: App\Controller\SiteController::Search

site_create:
    path: admin/site/create
    controller: App\Controller\SiteController::CreateSite

# Ville Controller

ville_list:
    path: admin/ville/create
    controller: App\Controller\VilleController::List

ville_update:
    path: /ville/update/{id}
    controller: App\Controller\VilleController::Update
    requirements:
        id: '\d+'

ville_delete:
    path: /ville/delete/{id}
    controller: App\Controller\VilleController::Delete
    requirements:
        id: '\d+'

ville_search:
    path: /ville
    controller: App\Controller\VilleController::Search

# Sortie Controller


sortie_create:
    path: /sortie/Create
    controller: App\Controller\SortieController::Create

sortie_update:
    path: /sortie/Update/{id}
    controller: App\Controller\SortieController::Update
    requirements:
        id: '\d+'

sortie_delete:
    path: /sortie/Delete/{id}
    controller: App\Controller\SortieController::Delete
    requirements:
        id: '\d+'


sortie_inscrire:
    path: /sortie/InscrireSortie/{idSortie}/{idParticipant}
    controller: App\Controller\SortieController::inscrireSortie
    requirements:
        idParticipant: '\d+'
        idSortie : '\d+'

sortie_desistement:
    path: /sortie/DesisterSortie/{idSortie}/{idParticipant}
    controller: App\Controller\SortieController::desisterSortie
    requirements:
        idParticipant: '\d+'
        idSortie : '\d+'

sortie_detail:
    path: /sortie/Detail/{id}
    controller: App\Controller\SortieController::Detail
    requirements:
        id: '\d+'

sortie_detail_public:
    path: /sortie/Detail/{id}
    controller: App\Controller\SortieController::Detail_public
    requirements:
        id: '\d+'

