# default controller

index:
    path: /
    controller: App\Controller\DefaultController::Index

index_site:
    path: /{idSite}
    controller: App\Controller\DefaultController::Index
    requirements:
        id: '\d+'

# security routing for user
security_login:
    path: /login
    controller: App\Controller\SecurityController::Login


security_account:
    path: /account/{id}
    controller: App\Controller\SecurityController::Account
    requirements:
        id: '\d+'

public_account:
    path: /account/visitor/{id}
    controller: App\Controller\UserController::Account
    requirements:
        id: '\d+'

# Site Controller
site_list:
    path: admin/site
    controller: App\Controller\SiteController::List

site_update:
    path: /site/update/
    controller: App\Controller\SiteController::Update


site_delete:
    path: /site/delete/{id}
    controller: App\Controller\SiteController::Delete
    requirements:
        id: '\d+'

site_search:
    path: /site
    controller: App\Controller\SiteController::Search

site_create:
    path: admin/site/create
    controller: App\Controller\SiteController::CreateSite

# Ville Controller

ville_list:
    path: admin/ville/create
    controller: App\Controller\VilleController::List

ville_update:
    path: /ville/update/
    controller: App\Controller\VilleController::Update

ville_delete:
    path: /ville/delete/{id}
    controller: App\Controller\VilleController::Delete
    requirements:
        id: '\d+'

ville_search:
    path: /ville
    controller: App\Controller\VilleController::Search

# Sortie Controller

sortie_create:
    path: /sortie/Create
    controller: App\Controller\SortieController::Create

sortie_update:
    path: /sortie/Update/{id}
    controller: App\Controller\SortieController::Update
    requirements:
        id: '\d+'

sortie_update_ville:
    path:  /sortie/Update/{idSortie}/{idLieu}
    controller: App\Controller\SortieController::UpdateListVille
    requirements:
        id: '/d+'


sortie_update_lieu:
    path: /sortie/Update/{idSortie}/{idVille}
    controller: App\Controller\SortieController::UpdateListLieu


sortie_delete:
    path: /sortie/Delete/{id}
    controller: App\Controller\SortieController::Delete
    requirements:
        id: '\d+'

sortie_inscrire:
    path: /sortie/InscrireSortie/{idSortie}/{idParticipant}
    controller: App\Controller\SortieController::inscrireSortie
    requirements:
        idParticipant: '\d+'
        idSortie : '\d+'

sortie_desistement:
    path: /sortie/DesisterSortie/{idSortie}/{idParticipant}
    controller: App\Controller\SortieController::desisterSortie
    requirements:
        idParticipant: '\d+'
        idSortie : '\d+'

sortie_detail:
    path: /sortie/Detail/{id}
    controller: App\Controller\SortieController::Detail
    requirements:
        id: '\d+'
